import { ArrowRight, Check, Database, LockKeyhole, ShieldCheck, ShoppingBag, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";

function Logo() { return <div className="flex items-center gap-2.5"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#b9ef72] text-[#183a3a]"><span className="font-serif text-[25px] font-bold">k</span></div><span className="text-[18px] font-bold tracking-[-.04em] text-[#183a3a]">kifaya<span className="text-[#6d9f48]">.</span></span></div>; }

export default function Landing() {
  return <div className="min-h-screen bg-[#f9f7f3] text-[#183a3a]">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Logo/><div className="flex items-center gap-2"><Link href="/login" className="hidden rounded-xl px-4 py-2.5 text-[12px] font-semibold text-[#43645f] sm:block">Se connecter</Link><Link href="/login"><Button className="h-10 rounded-xl bg-[#183a3a] px-4 text-[12px] font-semibold text-white">Créer mon espace <ArrowRight className="ml-2 h-3.5 w-3.5"/></Button></Link></div></header>
    <main>
      <section className="mx-auto max-w-7xl px-5 pb-20 pt-14 sm:px-8 lg:pt-24"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-[#dbe9cf] bg-[#f2faeb] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-[#5e873d]"><LockKeyhole className="h-3 w-3"/>Espace de travail sécurisé</div><h1 className="mt-6 text-[48px] font-bold leading-[.98] tracking-[-.075em] sm:text-[72px]">Gérez votre activité avec de <span className="text-[#6d9f48]">vraies données.</span></h1><p className="mt-6 max-w-2xl text-[16px] leading-relaxed text-[#6f7f79]">Kifaya Ops centralise vos commandes et vos clients dans une base persistante. Chaque compte voit uniquement ses propres données.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/login"><Button className="h-12 rounded-xl bg-[#183a3a] px-5 text-[13px] font-semibold text-white">Commencer gratuitement <ArrowRight className="ml-2 h-4 w-4"/></Button></Link><a href="#features" className="flex h-12 items-center justify-center rounded-xl border border-[#ddd9d0] bg-white px-5 text-[13px] font-semibold text-[#526b65]">Voir les fonctions</a></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-[11px] font-semibold text-[#788981]"><span className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-[#6da246]"/>Données persistantes</span><span className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-[#6da246]"/>RLS activé</span><span className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-[#6da246]"/>HTTPS</span></div></div></section>
      <section id="features" className="border-y border-[#e7e3dc] bg-white/50"><div className="mx-auto grid max-w-7xl gap-4 px-5 py-14 sm:px-8 md:grid-cols-3"><Feature icon={ShoppingBag} title="Commandes réelles" text="Créez, recherchez, exportez et faites avancer les statuts. Les données restent après fermeture du navigateur."/><Feature icon={UsersRound} title="Clients réels" text="Ajoutez vos contacts et retrouvez-les dans votre espace personnel, sans données de démonstration."/><Feature icon={ShieldCheck} title="Accès protégé" text="Supabase Auth et les politiques Row Level Security isolent les données de chaque utilisateur."/></div></section>
      <section id="security" className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="grid gap-8 rounded-3xl bg-[#183a3a] p-7 text-white sm:p-10 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#b9ef72]">Architecture</p><h2 className="mt-3 text-[30px] font-bold tracking-[-.05em]">Pas de faux bouton « connecter à Google Sheets ».</h2><p className="mt-3 max-w-2xl text-[13px] leading-relaxed text-white/60">Les intégrations externes doivent passer par un flux OAuth côté serveur. Cette version ne prétend pas synchroniser des données quand elle ne le fait pas.</p></div><Database className="hidden h-16 w-16 text-[#b9ef72] md:block"/></div></section>
    </main>
    <footer className="border-t border-[#e7e3dc] px-5 py-8 text-center text-[10px] text-[#89938f]">Kifaya Ops · espace de gestion</footer>
  </div>;
}
function Feature({icon:Icon,title,text}:{icon:typeof Database,title:string,text:string}) { return <div className="rounded-2xl border border-[#e5e2da] bg-[#fffdf9] p-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#e6f6d8] text-[#5d8a39]"><Icon className="h-5 w-5"/></div><h3 className="mt-5 text-[14px] font-bold">{title}</h3><p className="mt-2 text-[11px] leading-relaxed text-[#7e8b86]">{text}</p></div>; }
